In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
print(type(a), a.shape, a[1])

<class 'numpy.ndarray'> (3,) 2


In [15]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [17]:
print(b[1,1])

5


In [18]:
n1=np.zeros((2,2))
print(n1)

[[0. 0.]
 [0. 0.]]


In [19]:
n2 = np.ones((1,2))
print(n2)

[[1. 1.]]


In [20]:
n3 = np.full((2,2), 7)
print(n3)

[[7 7]
 [7 7]]


In [21]:
n4 = np.random.random((2,2));
print(n4)

[[0.28399114 0.69004394]
 [0.86213478 0.58840342]]


In [27]:
any_var=b[1,:2]
print(any_var)

[4 5]
