Hafidz Muhammad Rizky - 24084524 -  WIA1007 INTRODUCTION TO DATA SCIENCE

**Tutorial 3**

In [1]:
import numpy as np

In [11]:
# 1. Numpy Array of 2x2
npArr1 = np.array([[1,2], [3,4]])
print(npArr1)
print("Shape of:", npArr1.shape)

[[1 2]
 [3 4]]
Shape of: (2, 2)


In [14]:
# 2. Random Numpy Array with size of 3x4
npArr2 = np.random.random((3,4))
print(npArr2)
print("Shape of:",npArr2.shape)

[[0.23476344 0.82596335 0.17713961 0.3630822 ]
 [0.65163373 0.77360077 0.25958697 0.28962313]
 [0.34670057 0.56470318 0.56538808 0.93868944]]
Shape of: (3, 4)


In [15]:
# 3. Numpy Array of ones and zeros
npArr3 = np.ones((2,2))
npArr4 = np.zeros((2,2))
print(npArr3)
print("Shape of ones:", npArr3.shape)
print(npArr4)
print("Shape of zeros:", npArr4.shape)

[[1. 1.]
 [1. 1.]]
Shape of ones: (2, 2)
[[0. 0.]
 [0. 0.]]
Shape of zeros: (2, 2)


In [21]:
# 4. Random numpy arr of size 6x3, then transpose
npArr5 = np.random.random((6,3))
print("Normal:\n", npArr5)
npArr5_T = npArr5.T
print("Transposed:\n", npArr5_T)

Normal:
 [[0.89967104 0.96275251 0.02994053]
 [0.47061282 0.71718785 0.42545075]
 [0.36639708 0.73156115 0.83639311]
 [0.5715006  0.49029112 0.22569093]
 [0.74700904 0.20955128 0.05115911]
 [0.19941954 0.88478293 0.22617744]]
Transposed:
 [[0.89967104 0.47061282 0.36639708 0.5715006  0.74700904 0.19941954]
 [0.96275251 0.71718785 0.73156115 0.49029112 0.20955128 0.88478293]
 [0.02994053 0.42545075 0.83639311 0.22569093 0.05115911 0.22617744]]


In [60]:
# 5. Two random numpy array size of n x p, and p x m, then compute the dot product
n = np.random.randint(2,5)
p = np.random.randint(2,5)
m = np.random.randint(2,5)

npArr6 = np.random.random((n,p))
npArr7 = np.random.random((p,m))
print("First array:\n", npArr6, "\n Shape of first Array: ", npArr6.shape)
print("Second array:\n", npArr7, "\n Shape of second Array: ", npArr7.shape)

npArr8 = np.dot(npArr6, npArr7)
print("Dot product:\n", npArr8)

First array:
 [[0.50829969 0.21765135]
 [0.34691862 0.56121894]
 [0.74900374 0.29104898]
 [0.20829892 0.86397981]] 
 Shape of first Array:  (4, 2)
Second array:
 [[0.05347273 0.3117487  0.74863223 0.6839758 ]
 [0.23373019 0.25419771 0.7296569  0.18806924]] 
 Shape of second Array:  (2, 4)
Dot product:
 [[0.07805186 0.21378824 0.53934034 0.38859821]
 [0.1497245  0.250812   0.66921173 0.34283196]
 [0.10807821 0.30748493 0.77309424 0.56703779]
 [0.21307648 0.28455861 0.78634811 0.30495945]]
